# Generated by Django 3.0.1 on 2020-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
